[tools]
chezmoi = "2.72.1"
fzf = "0.74.3"
fx = "39.2.0"

git-lfs = "3.8.0"
ripgrep = "15.2.0"
terraform = "1.16.1"
lazydocker = "latest"
sops = "latest"

python = "3.14"
uv = "0.12.10"

node = "24"
pnpm = "11"
